// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcbspzocfjdtyimdmheq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjYnNwem9jZmpkdHlpbWRtaGVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTM0MzgsImV4cCI6MjA2Nzc4OTQzOH0.KkrdJqajIhdRBOvXrukZJ5jCo6vaZ4sFrbJY0R17igo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});